from Crud_Phyton.Database.ConexionDb import ConexionDb
from Crud_Phyton.Database.Cliente_Duplicated_Exception import Cliente_Duplicated_Exception
from Crud_Phyton.Database.Cliente_NotFound_Exception import Cliente_NotFound_Exception
import mysql.connector